[package]
name = "example_redis"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
fezz-sdk = { path = "../fezz-sdk" }
fezz-macros = { path = "../fezz-macros" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
redis = "0.27"
