[package]
name = "fezz-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
fezz-sdk = { path = "../fezz-sdk" }

