[package]
name = "hhrf"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
http-body-util = "0.1"
hyper-util = "0.1.3"
libloading = "0.8"
tokio = { version = "1", features = ["full"] }
fezz-sdk = { path = "../fezz-sdk" }
fezz-js = { path = "../fezz-js" }
